apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 2Gi
